        <div id="footer">
        	<ul id="block_various_links_footer" class="block_various_links">
            	<li class="first_item">Đồ án Xây dựng trang web bán Điện thoại di động</li><!--End .first_item-->
                <li class="item">Nhóm thực hiện: Hồ Nhật Quang - Nguyễn Hồng Sơn</li>
				<li class="item">Có tham khảo nguồn thông tin từ <a href="tgdd.com">www.tgdd.com</a></li>
                <li class="last_item">Powered by <a href="">X Signer Shop</a>&trade;</li><!--End .last_item-->
            </ul><!--End #block_various_links_footer-->
        </div><!--End #footer-->
    </div><!--End #page-->
</body>
</html>